// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: pkg/rabbit/api/rabbit.proto

package rabbit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RabbitMQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	ConsumeQueue  string                 `protobuf:"bytes,5,opt,name=consume_queue,json=consumeQueue,proto3" json:"consume_queue,omitempty"`
	PublicQueue   string                 `protobuf:"bytes,6,opt,name=public_queue,json=publicQueue,proto3" json:"public_queue,omitempty"`
	MaxConsumer   int32                  `protobuf:"varint,7,opt,name=max_consumer,json=maxConsumer,proto3" json:"max_consumer,omitempty"`
	ExpireTime    int32                  `protobuf:"varint,8,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RabbitMQ) Reset() {
	*x = RabbitMQ{}
	mi := &file_pkg_rabbit_api_rabbit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RabbitMQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RabbitMQ) ProtoMessage() {}

func (x *RabbitMQ) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rabbit_api_rabbit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RabbitMQ.ProtoReflect.Descriptor instead.
func (*RabbitMQ) Descriptor() ([]byte, []int) {
	return file_pkg_rabbit_api_rabbit_proto_rawDescGZIP(), []int{0}
}

func (x *RabbitMQ) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RabbitMQ) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RabbitMQ) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RabbitMQ) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RabbitMQ) GetConsumeQueue() string {
	if x != nil {
		return x.ConsumeQueue
	}
	return ""
}

func (x *RabbitMQ) GetPublicQueue() string {
	if x != nil {
		return x.PublicQueue
	}
	return ""
}

func (x *RabbitMQ) GetMaxConsumer() int32 {
	if x != nil {
		return x.MaxConsumer
	}
	return 0
}

func (x *RabbitMQ) GetExpireTime() int32 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

var File_pkg_rabbit_api_rabbit_proto protoreflect.FileDescriptor

var file_pkg_rabbit_api_rabbit_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x61, 0x62, 0x62, 0x69, 0x74, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x72, 0x61, 0x62, 0x62, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x67,
	0x72, 0x65, 0x79, 0x68, 0x6f, 0x6c, 0x65, 0x2e, 0x72, 0x61, 0x62, 0x62, 0x69, 0x74, 0x22, 0xfc,
	0x01, 0x0a, 0x08, 0x52, 0x61, 0x62, 0x62, 0x69, 0x74, 0x4d, 0x51, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x5f, 0x71, 0x75, 0x65,
	0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x61, 0x78,
	0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x1e, 0x5a,
	0x1c, 0x69, 0x72, 0x65, 0x6c, 0x69, 0x61, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x61, 0x62, 0x62,
	0x69, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x72, 0x61, 0x62, 0x62, 0x69, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pkg_rabbit_api_rabbit_proto_rawDescOnce sync.Once
	file_pkg_rabbit_api_rabbit_proto_rawDescData []byte
)

func file_pkg_rabbit_api_rabbit_proto_rawDescGZIP() []byte {
	file_pkg_rabbit_api_rabbit_proto_rawDescOnce.Do(func() {
		file_pkg_rabbit_api_rabbit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rabbit_api_rabbit_proto_rawDesc), len(file_pkg_rabbit_api_rabbit_proto_rawDesc)))
	})
	return file_pkg_rabbit_api_rabbit_proto_rawDescData
}

var file_pkg_rabbit_api_rabbit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_rabbit_api_rabbit_proto_goTypes = []any{
	(*RabbitMQ)(nil), // 0: greyhole.rabbit.RabbitMQ
}
var file_pkg_rabbit_api_rabbit_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_rabbit_api_rabbit_proto_init() }
func file_pkg_rabbit_api_rabbit_proto_init() {
	if File_pkg_rabbit_api_rabbit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rabbit_api_rabbit_proto_rawDesc), len(file_pkg_rabbit_api_rabbit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_rabbit_api_rabbit_proto_goTypes,
		DependencyIndexes: file_pkg_rabbit_api_rabbit_proto_depIdxs,
		MessageInfos:      file_pkg_rabbit_api_rabbit_proto_msgTypes,
	}.Build()
	File_pkg_rabbit_api_rabbit_proto = out.File
	file_pkg_rabbit_api_rabbit_proto_goTypes = nil
	file_pkg_rabbit_api_rabbit_proto_depIdxs = nil
}
