// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Interview is the predicate function for interview builders.
type Interview func(*sql.Selector)

// InterviewFavorite is the predicate function for interviewfavorite builders.
type InterviewFavorite func(*sql.Selector)

// PublicQuestion is the predicate function for publicquestion builders.
type PublicQuestion func(*sql.Selector)

// Question is the predicate function for question builders.
type Question func(*sql.Selector)
