// Code generated by ent, DO NOT EDIT.

package question

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the question type in the database.
	Label = "question"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldInterviewID holds the string denoting the interview_id field in the database.
	FieldInterviewID = "interview_id"
	// FieldQuestionIndex holds the string denoting the question_index field in the database.
	FieldQuestionIndex = "question_index"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldAudio holds the string denoting the audio field in the database.
	FieldAudio = "audio"
	// FieldLipsync holds the string denoting the lipsync field in the database.
	FieldLipsync = "lipsync"
	// FieldAnswer holds the string denoting the answer field in the database.
	FieldAnswer = "answer"
	// FieldRecordProof holds the string denoting the record_proof field in the database.
	FieldRecordProof = "record_proof"
	// FieldComment holds the string denoting the comment field in the database.
	FieldComment = "comment"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgeInterview holds the string denoting the interview edge name in mutations.
	EdgeInterview = "interview"
	// Table holds the table name of the question in the database.
	Table = "questions"
	// InterviewTable is the table that holds the interview relation/edge.
	InterviewTable = "questions"
	// InterviewInverseTable is the table name for the Interview entity.
	// It exists in this package in order to avoid circular dependency with the "interview" package.
	InterviewInverseTable = "interviews"
	// InterviewColumn is the table column denoting the interview relation/edge.
	InterviewColumn = "interview_id"
)

// Columns holds all SQL columns for question fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldInterviewID,
	FieldQuestionIndex,
	FieldContent,
	FieldAudio,
	FieldLipsync,
	FieldAnswer,
	FieldRecordProof,
	FieldComment,
	FieldScore,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// InterviewIDValidator is a validator for the "interview_id" field. It is called by the builders before save.
	InterviewIDValidator func(string) error
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator func(string) error
)

// OrderOption defines the ordering options for the Question queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByInterviewID orders the results by the interview_id field.
func ByInterviewID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInterviewID, opts...).ToFunc()
}

// ByQuestionIndex orders the results by the question_index field.
func ByQuestionIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuestionIndex, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByAudio orders the results by the audio field.
func ByAudio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAudio, opts...).ToFunc()
}

// ByAnswer orders the results by the answer field.
func ByAnswer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnswer, opts...).ToFunc()
}

// ByRecordProof orders the results by the record_proof field.
func ByRecordProof(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordProof, opts...).ToFunc()
}

// ByComment orders the results by the comment field.
func ByComment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComment, opts...).ToFunc()
}

// ByScore orders the results by the score field.
func ByScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScore, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByInterviewField orders the results by interview field.
func ByInterviewField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInterviewStep(), sql.OrderByField(field, opts...))
	}
}
func newInterviewStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InterviewInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InterviewTable, InterviewColumn),
	)
}
