// Code generated by ent, DO NOT EDIT.

package interviewfavorite

import (
	"irelia/pkg/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uint64) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldEQ(FieldUserID, v))
}

// InterviewID applies equality check predicate on the "interview_id" field. It's identical to InterviewIDEQ.
func InterviewID(v string) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldEQ(FieldInterviewID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uint64) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uint64) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uint64) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uint64) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uint64) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uint64) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uint64) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uint64) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldLTE(FieldUserID, v))
}

// InterviewIDEQ applies the EQ predicate on the "interview_id" field.
func InterviewIDEQ(v string) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldEQ(FieldInterviewID, v))
}

// InterviewIDNEQ applies the NEQ predicate on the "interview_id" field.
func InterviewIDNEQ(v string) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldNEQ(FieldInterviewID, v))
}

// InterviewIDIn applies the In predicate on the "interview_id" field.
func InterviewIDIn(vs ...string) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldIn(FieldInterviewID, vs...))
}

// InterviewIDNotIn applies the NotIn predicate on the "interview_id" field.
func InterviewIDNotIn(vs ...string) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldNotIn(FieldInterviewID, vs...))
}

// InterviewIDGT applies the GT predicate on the "interview_id" field.
func InterviewIDGT(v string) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldGT(FieldInterviewID, v))
}

// InterviewIDGTE applies the GTE predicate on the "interview_id" field.
func InterviewIDGTE(v string) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldGTE(FieldInterviewID, v))
}

// InterviewIDLT applies the LT predicate on the "interview_id" field.
func InterviewIDLT(v string) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldLT(FieldInterviewID, v))
}

// InterviewIDLTE applies the LTE predicate on the "interview_id" field.
func InterviewIDLTE(v string) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldLTE(FieldInterviewID, v))
}

// InterviewIDContains applies the Contains predicate on the "interview_id" field.
func InterviewIDContains(v string) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldContains(FieldInterviewID, v))
}

// InterviewIDHasPrefix applies the HasPrefix predicate on the "interview_id" field.
func InterviewIDHasPrefix(v string) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldHasPrefix(FieldInterviewID, v))
}

// InterviewIDHasSuffix applies the HasSuffix predicate on the "interview_id" field.
func InterviewIDHasSuffix(v string) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldHasSuffix(FieldInterviewID, v))
}

// InterviewIDEqualFold applies the EqualFold predicate on the "interview_id" field.
func InterviewIDEqualFold(v string) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldEqualFold(FieldInterviewID, v))
}

// InterviewIDContainsFold applies the ContainsFold predicate on the "interview_id" field.
func InterviewIDContainsFold(v string) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.FieldContainsFold(FieldInterviewID, v))
}

// HasInterview applies the HasEdge predicate on the "interview" edge.
func HasInterview() predicate.InterviewFavorite {
	return predicate.InterviewFavorite(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InterviewTable, InterviewColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInterviewWith applies the HasEdge predicate on the "interview" edge with a given conditions (other predicates).
func HasInterviewWith(preds ...predicate.Interview) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(func(s *sql.Selector) {
		step := newInterviewStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InterviewFavorite) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InterviewFavorite) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InterviewFavorite) predicate.InterviewFavorite {
	return predicate.InterviewFavorite(sql.NotPredicates(p))
}
