server:
  host: 0.0.0.0
  port: 3140
  gwport: 3141

karma:
  url: "http://localhost:5000/api/lip-sync"

darius:
  genurl: "http://35.198.194.208:30012/darius/v1/suggest_interview_question"
  scrurl: "http://35.198.194.208:30012/darius/v1/score_interview"

db:
  type: ${DB_TYPE}
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  name: ${DB_NAME}

questions_to_prepare: 1