// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"irelia/pkg/ent/interviewfavorite"
	"irelia/pkg/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InterviewFavoriteDelete is the builder for deleting a InterviewFavorite entity.
type InterviewFavoriteDelete struct {
	config
	hooks    []Hook
	mutation *InterviewFavoriteMutation
}

// Where appends a list predicates to the InterviewFavoriteDelete builder.
func (ifd *InterviewFavoriteDelete) Where(ps ...predicate.InterviewFavorite) *InterviewFavoriteDelete {
	ifd.mutation.Where(ps...)
	return ifd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ifd *InterviewFavoriteDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ifd.sqlExec, ifd.mutation, ifd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ifd *InterviewFavoriteDelete) ExecX(ctx context.Context) int {
	n, err := ifd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ifd *InterviewFavoriteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(interviewfavorite.Table, sqlgraph.NewFieldSpec(interviewfavorite.FieldID, field.TypeInt))
	if ps := ifd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ifd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ifd.mutation.done = true
	return affected, err
}

// InterviewFavoriteDeleteOne is the builder for deleting a single InterviewFavorite entity.
type InterviewFavoriteDeleteOne struct {
	ifd *InterviewFavoriteDelete
}

// Where appends a list predicates to the InterviewFavoriteDelete builder.
func (ifdo *InterviewFavoriteDeleteOne) Where(ps ...predicate.InterviewFavorite) *InterviewFavoriteDeleteOne {
	ifdo.ifd.mutation.Where(ps...)
	return ifdo
}

// Exec executes the deletion query.
func (ifdo *InterviewFavoriteDeleteOne) Exec(ctx context.Context) error {
	n, err := ifdo.ifd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{interviewfavorite.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ifdo *InterviewFavoriteDeleteOne) ExecX(ctx context.Context) {
	if err := ifdo.Exec(ctx); err != nil {
		panic(err)
	}
}
