// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"irelia/pkg/ent/predicate"
	"irelia/pkg/ent/publicquestion"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PublicQuestionQuery is the builder for querying PublicQuestion entities.
type PublicQuestionQuery struct {
	config
	ctx        *QueryContext
	order      []publicquestion.OrderOption
	inters     []Interceptor
	predicates []predicate.PublicQuestion
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PublicQuestionQuery builder.
func (pqq *PublicQuestionQuery) Where(ps ...predicate.PublicQuestion) *PublicQuestionQuery {
	pqq.predicates = append(pqq.predicates, ps...)
	return pqq
}

// Limit the number of records to be returned by this query.
func (pqq *PublicQuestionQuery) Limit(limit int) *PublicQuestionQuery {
	pqq.ctx.Limit = &limit
	return pqq
}

// Offset to start from.
func (pqq *PublicQuestionQuery) Offset(offset int) *PublicQuestionQuery {
	pqq.ctx.Offset = &offset
	return pqq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pqq *PublicQuestionQuery) Unique(unique bool) *PublicQuestionQuery {
	pqq.ctx.Unique = &unique
	return pqq
}

// Order specifies how the records should be ordered.
func (pqq *PublicQuestionQuery) Order(o ...publicquestion.OrderOption) *PublicQuestionQuery {
	pqq.order = append(pqq.order, o...)
	return pqq
}

// First returns the first PublicQuestion entity from the query.
// Returns a *NotFoundError when no PublicQuestion was found.
func (pqq *PublicQuestionQuery) First(ctx context.Context) (*PublicQuestion, error) {
	nodes, err := pqq.Limit(1).All(setContextOp(ctx, pqq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{publicquestion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pqq *PublicQuestionQuery) FirstX(ctx context.Context) *PublicQuestion {
	node, err := pqq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PublicQuestion ID from the query.
// Returns a *NotFoundError when no PublicQuestion ID was found.
func (pqq *PublicQuestionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pqq.Limit(1).IDs(setContextOp(ctx, pqq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{publicquestion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pqq *PublicQuestionQuery) FirstIDX(ctx context.Context) int {
	id, err := pqq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PublicQuestion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PublicQuestion entity is found.
// Returns a *NotFoundError when no PublicQuestion entities are found.
func (pqq *PublicQuestionQuery) Only(ctx context.Context) (*PublicQuestion, error) {
	nodes, err := pqq.Limit(2).All(setContextOp(ctx, pqq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{publicquestion.Label}
	default:
		return nil, &NotSingularError{publicquestion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pqq *PublicQuestionQuery) OnlyX(ctx context.Context) *PublicQuestion {
	node, err := pqq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PublicQuestion ID in the query.
// Returns a *NotSingularError when more than one PublicQuestion ID is found.
// Returns a *NotFoundError when no entities are found.
func (pqq *PublicQuestionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pqq.Limit(2).IDs(setContextOp(ctx, pqq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{publicquestion.Label}
	default:
		err = &NotSingularError{publicquestion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pqq *PublicQuestionQuery) OnlyIDX(ctx context.Context) int {
	id, err := pqq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PublicQuestions.
func (pqq *PublicQuestionQuery) All(ctx context.Context) ([]*PublicQuestion, error) {
	ctx = setContextOp(ctx, pqq.ctx, ent.OpQueryAll)
	if err := pqq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PublicQuestion, *PublicQuestionQuery]()
	return withInterceptors[[]*PublicQuestion](ctx, pqq, qr, pqq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pqq *PublicQuestionQuery) AllX(ctx context.Context) []*PublicQuestion {
	nodes, err := pqq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PublicQuestion IDs.
func (pqq *PublicQuestionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if pqq.ctx.Unique == nil && pqq.path != nil {
		pqq.Unique(true)
	}
	ctx = setContextOp(ctx, pqq.ctx, ent.OpQueryIDs)
	if err = pqq.Select(publicquestion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pqq *PublicQuestionQuery) IDsX(ctx context.Context) []int {
	ids, err := pqq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pqq *PublicQuestionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pqq.ctx, ent.OpQueryCount)
	if err := pqq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pqq, querierCount[*PublicQuestionQuery](), pqq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pqq *PublicQuestionQuery) CountX(ctx context.Context) int {
	count, err := pqq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pqq *PublicQuestionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pqq.ctx, ent.OpQueryExist)
	switch _, err := pqq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pqq *PublicQuestionQuery) ExistX(ctx context.Context) bool {
	exist, err := pqq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PublicQuestionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pqq *PublicQuestionQuery) Clone() *PublicQuestionQuery {
	if pqq == nil {
		return nil
	}
	return &PublicQuestionQuery{
		config:     pqq.config,
		ctx:        pqq.ctx.Clone(),
		order:      append([]publicquestion.OrderOption{}, pqq.order...),
		inters:     append([]Interceptor{}, pqq.inters...),
		predicates: append([]predicate.PublicQuestion{}, pqq.predicates...),
		// clone intermediate query.
		sql:  pqq.sql.Clone(),
		path: pqq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PublicQuestion.Query().
//		GroupBy(publicquestion.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pqq *PublicQuestionQuery) GroupBy(field string, fields ...string) *PublicQuestionGroupBy {
	pqq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PublicQuestionGroupBy{build: pqq}
	grbuild.flds = &pqq.ctx.Fields
	grbuild.label = publicquestion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.PublicQuestion.Query().
//		Select(publicquestion.FieldCreatedAt).
//		Scan(ctx, &v)
func (pqq *PublicQuestionQuery) Select(fields ...string) *PublicQuestionSelect {
	pqq.ctx.Fields = append(pqq.ctx.Fields, fields...)
	sbuild := &PublicQuestionSelect{PublicQuestionQuery: pqq}
	sbuild.label = publicquestion.Label
	sbuild.flds, sbuild.scan = &pqq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PublicQuestionSelect configured with the given aggregations.
func (pqq *PublicQuestionQuery) Aggregate(fns ...AggregateFunc) *PublicQuestionSelect {
	return pqq.Select().Aggregate(fns...)
}

func (pqq *PublicQuestionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pqq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pqq); err != nil {
				return err
			}
		}
	}
	for _, f := range pqq.ctx.Fields {
		if !publicquestion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pqq.path != nil {
		prev, err := pqq.path(ctx)
		if err != nil {
			return err
		}
		pqq.sql = prev
	}
	return nil
}

func (pqq *PublicQuestionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PublicQuestion, error) {
	var (
		nodes = []*PublicQuestion{}
		_spec = pqq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PublicQuestion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PublicQuestion{config: pqq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pqq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (pqq *PublicQuestionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pqq.querySpec()
	_spec.Node.Columns = pqq.ctx.Fields
	if len(pqq.ctx.Fields) > 0 {
		_spec.Unique = pqq.ctx.Unique != nil && *pqq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pqq.driver, _spec)
}

func (pqq *PublicQuestionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(publicquestion.Table, publicquestion.Columns, sqlgraph.NewFieldSpec(publicquestion.FieldID, field.TypeInt))
	_spec.From = pqq.sql
	if unique := pqq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pqq.path != nil {
		_spec.Unique = true
	}
	if fields := pqq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, publicquestion.FieldID)
		for i := range fields {
			if fields[i] != publicquestion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pqq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pqq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pqq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pqq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pqq *PublicQuestionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pqq.driver.Dialect())
	t1 := builder.Table(publicquestion.Table)
	columns := pqq.ctx.Fields
	if len(columns) == 0 {
		columns = publicquestion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pqq.sql != nil {
		selector = pqq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pqq.ctx.Unique != nil && *pqq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pqq.predicates {
		p(selector)
	}
	for _, p := range pqq.order {
		p(selector)
	}
	if offset := pqq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pqq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PublicQuestionGroupBy is the group-by builder for PublicQuestion entities.
type PublicQuestionGroupBy struct {
	selector
	build *PublicQuestionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pqgb *PublicQuestionGroupBy) Aggregate(fns ...AggregateFunc) *PublicQuestionGroupBy {
	pqgb.fns = append(pqgb.fns, fns...)
	return pqgb
}

// Scan applies the selector query and scans the result into the given value.
func (pqgb *PublicQuestionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pqgb.build.ctx, ent.OpQueryGroupBy)
	if err := pqgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PublicQuestionQuery, *PublicQuestionGroupBy](ctx, pqgb.build, pqgb, pqgb.build.inters, v)
}

func (pqgb *PublicQuestionGroupBy) sqlScan(ctx context.Context, root *PublicQuestionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pqgb.fns))
	for _, fn := range pqgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pqgb.flds)+len(pqgb.fns))
		for _, f := range *pqgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pqgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pqgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PublicQuestionSelect is the builder for selecting fields of PublicQuestion entities.
type PublicQuestionSelect struct {
	*PublicQuestionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pqs *PublicQuestionSelect) Aggregate(fns ...AggregateFunc) *PublicQuestionSelect {
	pqs.fns = append(pqs.fns, fns...)
	return pqs
}

// Scan applies the selector query and scans the result into the given value.
func (pqs *PublicQuestionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pqs.ctx, ent.OpQuerySelect)
	if err := pqs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PublicQuestionQuery, *PublicQuestionSelect](ctx, pqs.PublicQuestionQuery, pqs, pqs.inters, v)
}

func (pqs *PublicQuestionSelect) sqlScan(ctx context.Context, root *PublicQuestionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pqs.fns))
	for _, fn := range pqs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pqs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pqs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
