// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	irelia "irelia/api"
	"irelia/pkg/ent/predicate"
	"irelia/pkg/ent/question"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuestionUpdate is the builder for updating Question entities.
type QuestionUpdate struct {
	config
	hooks     []Hook
	mutation  *QuestionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the QuestionUpdate builder.
func (qu *QuestionUpdate) Where(ps ...predicate.Question) *QuestionUpdate {
	qu.mutation.Where(ps...)
	return qu
}

// SetUpdatedAt sets the "updated_at" field.
func (qu *QuestionUpdate) SetUpdatedAt(t time.Time) *QuestionUpdate {
	qu.mutation.SetUpdatedAt(t)
	return qu
}

// SetContent sets the "content" field.
func (qu *QuestionUpdate) SetContent(s string) *QuestionUpdate {
	qu.mutation.SetContent(s)
	return qu
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (qu *QuestionUpdate) SetNillableContent(s *string) *QuestionUpdate {
	if s != nil {
		qu.SetContent(*s)
	}
	return qu
}

// SetAudio sets the "audio" field.
func (qu *QuestionUpdate) SetAudio(s string) *QuestionUpdate {
	qu.mutation.SetAudio(s)
	return qu
}

// SetNillableAudio sets the "audio" field if the given value is not nil.
func (qu *QuestionUpdate) SetNillableAudio(s *string) *QuestionUpdate {
	if s != nil {
		qu.SetAudio(*s)
	}
	return qu
}

// ClearAudio clears the value of the "audio" field.
func (qu *QuestionUpdate) ClearAudio() *QuestionUpdate {
	qu.mutation.ClearAudio()
	return qu
}

// SetLipsync sets the "lipsync" field.
func (qu *QuestionUpdate) SetLipsync(isd *irelia.LipSyncData) *QuestionUpdate {
	qu.mutation.SetLipsync(isd)
	return qu
}

// ClearLipsync clears the value of the "lipsync" field.
func (qu *QuestionUpdate) ClearLipsync() *QuestionUpdate {
	qu.mutation.ClearLipsync()
	return qu
}

// SetAnswer sets the "answer" field.
func (qu *QuestionUpdate) SetAnswer(s string) *QuestionUpdate {
	qu.mutation.SetAnswer(s)
	return qu
}

// SetNillableAnswer sets the "answer" field if the given value is not nil.
func (qu *QuestionUpdate) SetNillableAnswer(s *string) *QuestionUpdate {
	if s != nil {
		qu.SetAnswer(*s)
	}
	return qu
}

// ClearAnswer clears the value of the "answer" field.
func (qu *QuestionUpdate) ClearAnswer() *QuestionUpdate {
	qu.mutation.ClearAnswer()
	return qu
}

// SetRecordProof sets the "record_proof" field.
func (qu *QuestionUpdate) SetRecordProof(s string) *QuestionUpdate {
	qu.mutation.SetRecordProof(s)
	return qu
}

// SetNillableRecordProof sets the "record_proof" field if the given value is not nil.
func (qu *QuestionUpdate) SetNillableRecordProof(s *string) *QuestionUpdate {
	if s != nil {
		qu.SetRecordProof(*s)
	}
	return qu
}

// ClearRecordProof clears the value of the "record_proof" field.
func (qu *QuestionUpdate) ClearRecordProof() *QuestionUpdate {
	qu.mutation.ClearRecordProof()
	return qu
}

// SetComment sets the "comment" field.
func (qu *QuestionUpdate) SetComment(s string) *QuestionUpdate {
	qu.mutation.SetComment(s)
	return qu
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (qu *QuestionUpdate) SetNillableComment(s *string) *QuestionUpdate {
	if s != nil {
		qu.SetComment(*s)
	}
	return qu
}

// ClearComment clears the value of the "comment" field.
func (qu *QuestionUpdate) ClearComment() *QuestionUpdate {
	qu.mutation.ClearComment()
	return qu
}

// SetScore sets the "score" field.
func (qu *QuestionUpdate) SetScore(s string) *QuestionUpdate {
	qu.mutation.SetScore(s)
	return qu
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (qu *QuestionUpdate) SetNillableScore(s *string) *QuestionUpdate {
	if s != nil {
		qu.SetScore(*s)
	}
	return qu
}

// ClearScore clears the value of the "score" field.
func (qu *QuestionUpdate) ClearScore() *QuestionUpdate {
	qu.mutation.ClearScore()
	return qu
}

// SetStatus sets the "status" field.
func (qu *QuestionUpdate) SetStatus(is irelia.QuestionStatus) *QuestionUpdate {
	qu.mutation.ResetStatus()
	qu.mutation.SetStatus(is)
	return qu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (qu *QuestionUpdate) SetNillableStatus(is *irelia.QuestionStatus) *QuestionUpdate {
	if is != nil {
		qu.SetStatus(*is)
	}
	return qu
}

// AddStatus adds is to the "status" field.
func (qu *QuestionUpdate) AddStatus(is irelia.QuestionStatus) *QuestionUpdate {
	qu.mutation.AddStatus(is)
	return qu
}

// Mutation returns the QuestionMutation object of the builder.
func (qu *QuestionUpdate) Mutation() *QuestionMutation {
	return qu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (qu *QuestionUpdate) Save(ctx context.Context) (int, error) {
	qu.defaults()
	return withHooks(ctx, qu.sqlSave, qu.mutation, qu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (qu *QuestionUpdate) SaveX(ctx context.Context) int {
	affected, err := qu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (qu *QuestionUpdate) Exec(ctx context.Context) error {
	_, err := qu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qu *QuestionUpdate) ExecX(ctx context.Context) {
	if err := qu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (qu *QuestionUpdate) defaults() {
	if _, ok := qu.mutation.UpdatedAt(); !ok {
		v := question.UpdateDefaultUpdatedAt()
		qu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (qu *QuestionUpdate) check() error {
	if v, ok := qu.mutation.Content(); ok {
		if err := question.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Question.content": %w`, err)}
		}
	}
	if qu.mutation.InterviewCleared() && len(qu.mutation.InterviewIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Question.interview"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (qu *QuestionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *QuestionUpdate {
	qu.modifiers = append(qu.modifiers, modifiers...)
	return qu
}

func (qu *QuestionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := qu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(question.Table, question.Columns, sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt))
	if ps := qu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := qu.mutation.UpdatedAt(); ok {
		_spec.SetField(question.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := qu.mutation.Content(); ok {
		_spec.SetField(question.FieldContent, field.TypeString, value)
	}
	if value, ok := qu.mutation.Audio(); ok {
		_spec.SetField(question.FieldAudio, field.TypeString, value)
	}
	if qu.mutation.AudioCleared() {
		_spec.ClearField(question.FieldAudio, field.TypeString)
	}
	if value, ok := qu.mutation.Lipsync(); ok {
		_spec.SetField(question.FieldLipsync, field.TypeJSON, value)
	}
	if qu.mutation.LipsyncCleared() {
		_spec.ClearField(question.FieldLipsync, field.TypeJSON)
	}
	if value, ok := qu.mutation.Answer(); ok {
		_spec.SetField(question.FieldAnswer, field.TypeString, value)
	}
	if qu.mutation.AnswerCleared() {
		_spec.ClearField(question.FieldAnswer, field.TypeString)
	}
	if value, ok := qu.mutation.RecordProof(); ok {
		_spec.SetField(question.FieldRecordProof, field.TypeString, value)
	}
	if qu.mutation.RecordProofCleared() {
		_spec.ClearField(question.FieldRecordProof, field.TypeString)
	}
	if value, ok := qu.mutation.Comment(); ok {
		_spec.SetField(question.FieldComment, field.TypeString, value)
	}
	if qu.mutation.CommentCleared() {
		_spec.ClearField(question.FieldComment, field.TypeString)
	}
	if value, ok := qu.mutation.Score(); ok {
		_spec.SetField(question.FieldScore, field.TypeString, value)
	}
	if qu.mutation.ScoreCleared() {
		_spec.ClearField(question.FieldScore, field.TypeString)
	}
	if value, ok := qu.mutation.Status(); ok {
		_spec.SetField(question.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := qu.mutation.AddedStatus(); ok {
		_spec.AddField(question.FieldStatus, field.TypeInt32, value)
	}
	_spec.AddModifiers(qu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, qu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{question.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	qu.mutation.done = true
	return n, nil
}

// QuestionUpdateOne is the builder for updating a single Question entity.
type QuestionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *QuestionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (quo *QuestionUpdateOne) SetUpdatedAt(t time.Time) *QuestionUpdateOne {
	quo.mutation.SetUpdatedAt(t)
	return quo
}

// SetContent sets the "content" field.
func (quo *QuestionUpdateOne) SetContent(s string) *QuestionUpdateOne {
	quo.mutation.SetContent(s)
	return quo
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (quo *QuestionUpdateOne) SetNillableContent(s *string) *QuestionUpdateOne {
	if s != nil {
		quo.SetContent(*s)
	}
	return quo
}

// SetAudio sets the "audio" field.
func (quo *QuestionUpdateOne) SetAudio(s string) *QuestionUpdateOne {
	quo.mutation.SetAudio(s)
	return quo
}

// SetNillableAudio sets the "audio" field if the given value is not nil.
func (quo *QuestionUpdateOne) SetNillableAudio(s *string) *QuestionUpdateOne {
	if s != nil {
		quo.SetAudio(*s)
	}
	return quo
}

// ClearAudio clears the value of the "audio" field.
func (quo *QuestionUpdateOne) ClearAudio() *QuestionUpdateOne {
	quo.mutation.ClearAudio()
	return quo
}

// SetLipsync sets the "lipsync" field.
func (quo *QuestionUpdateOne) SetLipsync(isd *irelia.LipSyncData) *QuestionUpdateOne {
	quo.mutation.SetLipsync(isd)
	return quo
}

// ClearLipsync clears the value of the "lipsync" field.
func (quo *QuestionUpdateOne) ClearLipsync() *QuestionUpdateOne {
	quo.mutation.ClearLipsync()
	return quo
}

// SetAnswer sets the "answer" field.
func (quo *QuestionUpdateOne) SetAnswer(s string) *QuestionUpdateOne {
	quo.mutation.SetAnswer(s)
	return quo
}

// SetNillableAnswer sets the "answer" field if the given value is not nil.
func (quo *QuestionUpdateOne) SetNillableAnswer(s *string) *QuestionUpdateOne {
	if s != nil {
		quo.SetAnswer(*s)
	}
	return quo
}

// ClearAnswer clears the value of the "answer" field.
func (quo *QuestionUpdateOne) ClearAnswer() *QuestionUpdateOne {
	quo.mutation.ClearAnswer()
	return quo
}

// SetRecordProof sets the "record_proof" field.
func (quo *QuestionUpdateOne) SetRecordProof(s string) *QuestionUpdateOne {
	quo.mutation.SetRecordProof(s)
	return quo
}

// SetNillableRecordProof sets the "record_proof" field if the given value is not nil.
func (quo *QuestionUpdateOne) SetNillableRecordProof(s *string) *QuestionUpdateOne {
	if s != nil {
		quo.SetRecordProof(*s)
	}
	return quo
}

// ClearRecordProof clears the value of the "record_proof" field.
func (quo *QuestionUpdateOne) ClearRecordProof() *QuestionUpdateOne {
	quo.mutation.ClearRecordProof()
	return quo
}

// SetComment sets the "comment" field.
func (quo *QuestionUpdateOne) SetComment(s string) *QuestionUpdateOne {
	quo.mutation.SetComment(s)
	return quo
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (quo *QuestionUpdateOne) SetNillableComment(s *string) *QuestionUpdateOne {
	if s != nil {
		quo.SetComment(*s)
	}
	return quo
}

// ClearComment clears the value of the "comment" field.
func (quo *QuestionUpdateOne) ClearComment() *QuestionUpdateOne {
	quo.mutation.ClearComment()
	return quo
}

// SetScore sets the "score" field.
func (quo *QuestionUpdateOne) SetScore(s string) *QuestionUpdateOne {
	quo.mutation.SetScore(s)
	return quo
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (quo *QuestionUpdateOne) SetNillableScore(s *string) *QuestionUpdateOne {
	if s != nil {
		quo.SetScore(*s)
	}
	return quo
}

// ClearScore clears the value of the "score" field.
func (quo *QuestionUpdateOne) ClearScore() *QuestionUpdateOne {
	quo.mutation.ClearScore()
	return quo
}

// SetStatus sets the "status" field.
func (quo *QuestionUpdateOne) SetStatus(is irelia.QuestionStatus) *QuestionUpdateOne {
	quo.mutation.ResetStatus()
	quo.mutation.SetStatus(is)
	return quo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (quo *QuestionUpdateOne) SetNillableStatus(is *irelia.QuestionStatus) *QuestionUpdateOne {
	if is != nil {
		quo.SetStatus(*is)
	}
	return quo
}

// AddStatus adds is to the "status" field.
func (quo *QuestionUpdateOne) AddStatus(is irelia.QuestionStatus) *QuestionUpdateOne {
	quo.mutation.AddStatus(is)
	return quo
}

// Mutation returns the QuestionMutation object of the builder.
func (quo *QuestionUpdateOne) Mutation() *QuestionMutation {
	return quo.mutation
}

// Where appends a list predicates to the QuestionUpdate builder.
func (quo *QuestionUpdateOne) Where(ps ...predicate.Question) *QuestionUpdateOne {
	quo.mutation.Where(ps...)
	return quo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (quo *QuestionUpdateOne) Select(field string, fields ...string) *QuestionUpdateOne {
	quo.fields = append([]string{field}, fields...)
	return quo
}

// Save executes the query and returns the updated Question entity.
func (quo *QuestionUpdateOne) Save(ctx context.Context) (*Question, error) {
	quo.defaults()
	return withHooks(ctx, quo.sqlSave, quo.mutation, quo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (quo *QuestionUpdateOne) SaveX(ctx context.Context) *Question {
	node, err := quo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (quo *QuestionUpdateOne) Exec(ctx context.Context) error {
	_, err := quo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (quo *QuestionUpdateOne) ExecX(ctx context.Context) {
	if err := quo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (quo *QuestionUpdateOne) defaults() {
	if _, ok := quo.mutation.UpdatedAt(); !ok {
		v := question.UpdateDefaultUpdatedAt()
		quo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (quo *QuestionUpdateOne) check() error {
	if v, ok := quo.mutation.Content(); ok {
		if err := question.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Question.content": %w`, err)}
		}
	}
	if quo.mutation.InterviewCleared() && len(quo.mutation.InterviewIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Question.interview"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (quo *QuestionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *QuestionUpdateOne {
	quo.modifiers = append(quo.modifiers, modifiers...)
	return quo
}

func (quo *QuestionUpdateOne) sqlSave(ctx context.Context) (_node *Question, err error) {
	if err := quo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(question.Table, question.Columns, sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt))
	id, ok := quo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Question.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := quo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, question.FieldID)
		for _, f := range fields {
			if !question.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != question.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := quo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := quo.mutation.UpdatedAt(); ok {
		_spec.SetField(question.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := quo.mutation.Content(); ok {
		_spec.SetField(question.FieldContent, field.TypeString, value)
	}
	if value, ok := quo.mutation.Audio(); ok {
		_spec.SetField(question.FieldAudio, field.TypeString, value)
	}
	if quo.mutation.AudioCleared() {
		_spec.ClearField(question.FieldAudio, field.TypeString)
	}
	if value, ok := quo.mutation.Lipsync(); ok {
		_spec.SetField(question.FieldLipsync, field.TypeJSON, value)
	}
	if quo.mutation.LipsyncCleared() {
		_spec.ClearField(question.FieldLipsync, field.TypeJSON)
	}
	if value, ok := quo.mutation.Answer(); ok {
		_spec.SetField(question.FieldAnswer, field.TypeString, value)
	}
	if quo.mutation.AnswerCleared() {
		_spec.ClearField(question.FieldAnswer, field.TypeString)
	}
	if value, ok := quo.mutation.RecordProof(); ok {
		_spec.SetField(question.FieldRecordProof, field.TypeString, value)
	}
	if quo.mutation.RecordProofCleared() {
		_spec.ClearField(question.FieldRecordProof, field.TypeString)
	}
	if value, ok := quo.mutation.Comment(); ok {
		_spec.SetField(question.FieldComment, field.TypeString, value)
	}
	if quo.mutation.CommentCleared() {
		_spec.ClearField(question.FieldComment, field.TypeString)
	}
	if value, ok := quo.mutation.Score(); ok {
		_spec.SetField(question.FieldScore, field.TypeString, value)
	}
	if quo.mutation.ScoreCleared() {
		_spec.ClearField(question.FieldScore, field.TypeString)
	}
	if value, ok := quo.mutation.Status(); ok {
		_spec.SetField(question.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := quo.mutation.AddedStatus(); ok {
		_spec.AddField(question.FieldStatus, field.TypeInt32, value)
	}
	_spec.AddModifiers(quo.modifiers...)
	_node = &Question{config: quo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, quo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{question.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	quo.mutation.done = true
	return _node, nil
}
