// Code generated by ent, DO NOT EDIT.

package ent

import (
	"irelia/pkg/ent/interview"
	"irelia/pkg/ent/interviewfavorite"
	"irelia/pkg/ent/question"
	"irelia/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	interviewMixin := schema.Interview{}.Mixin()
	interviewMixinFields0 := interviewMixin[0].Fields()
	_ = interviewMixinFields0
	interviewFields := schema.Interview{}.Fields()
	_ = interviewFields
	// interviewDescCreatedAt is the schema descriptor for created_at field.
	interviewDescCreatedAt := interviewMixinFields0[0].Descriptor()
	// interview.DefaultCreatedAt holds the default value on creation for the created_at field.
	interview.DefaultCreatedAt = interviewDescCreatedAt.Default.(func() time.Time)
	// interviewDescUpdatedAt is the schema descriptor for updated_at field.
	interviewDescUpdatedAt := interviewMixinFields0[1].Descriptor()
	// interview.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	interview.DefaultUpdatedAt = interviewDescUpdatedAt.Default.(func() time.Time)
	// interview.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	interview.UpdateDefaultUpdatedAt = interviewDescUpdatedAt.UpdateDefault.(func() time.Time)
	// interviewDescPosition is the schema descriptor for position field.
	interviewDescPosition := interviewFields[2].Descriptor()
	// interview.PositionValidator is a validator for the "position" field. It is called by the builders before save.
	interview.PositionValidator = interviewDescPosition.Validators[0].(func(string) error)
	// interviewDescLanguage is the schema descriptor for language field.
	interviewDescLanguage := interviewFields[4].Descriptor()
	// interview.LanguageValidator is a validator for the "language" field. It is called by the builders before save.
	interview.LanguageValidator = interviewDescLanguage.Validators[0].(func(string) error)
	// interviewDescSpeed is the schema descriptor for speed field.
	interviewDescSpeed := interviewFields[6].Descriptor()
	// interview.DefaultSpeed holds the default value on creation for the speed field.
	interview.DefaultSpeed = interviewDescSpeed.Default.(int32)
	// interviewDescSkipCode is the schema descriptor for skip_code field.
	interviewDescSkipCode := interviewFields[9].Descriptor()
	// interview.DefaultSkipCode holds the default value on creation for the skip_code field.
	interview.DefaultSkipCode = interviewDescSkipCode.Default.(bool)
	// interviewDescTotalQuestions is the schema descriptor for total_questions field.
	interviewDescTotalQuestions := interviewFields[10].Descriptor()
	// interview.DefaultTotalQuestions holds the default value on creation for the total_questions field.
	interview.DefaultTotalQuestions = interviewDescTotalQuestions.Default.(int32)
	// interviewDescRemainingQuestions is the schema descriptor for remaining_questions field.
	interviewDescRemainingQuestions := interviewFields[11].Descriptor()
	// interview.DefaultRemainingQuestions holds the default value on creation for the remaining_questions field.
	interview.DefaultRemainingQuestions = interviewDescRemainingQuestions.Default.(int32)
	interviewfavoriteMixin := schema.InterviewFavorite{}.Mixin()
	interviewfavoriteMixinFields0 := interviewfavoriteMixin[0].Fields()
	_ = interviewfavoriteMixinFields0
	interviewfavoriteFields := schema.InterviewFavorite{}.Fields()
	_ = interviewfavoriteFields
	// interviewfavoriteDescCreatedAt is the schema descriptor for created_at field.
	interviewfavoriteDescCreatedAt := interviewfavoriteMixinFields0[0].Descriptor()
	// interviewfavorite.DefaultCreatedAt holds the default value on creation for the created_at field.
	interviewfavorite.DefaultCreatedAt = interviewfavoriteDescCreatedAt.Default.(func() time.Time)
	// interviewfavoriteDescUpdatedAt is the schema descriptor for updated_at field.
	interviewfavoriteDescUpdatedAt := interviewfavoriteMixinFields0[1].Descriptor()
	// interviewfavorite.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	interviewfavorite.DefaultUpdatedAt = interviewfavoriteDescUpdatedAt.Default.(func() time.Time)
	// interviewfavorite.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	interviewfavorite.UpdateDefaultUpdatedAt = interviewfavoriteDescUpdatedAt.UpdateDefault.(func() time.Time)
	questionMixin := schema.Question{}.Mixin()
	questionMixinFields0 := questionMixin[0].Fields()
	_ = questionMixinFields0
	questionFields := schema.Question{}.Fields()
	_ = questionFields
	// questionDescCreatedAt is the schema descriptor for created_at field.
	questionDescCreatedAt := questionMixinFields0[0].Descriptor()
	// question.DefaultCreatedAt holds the default value on creation for the created_at field.
	question.DefaultCreatedAt = questionDescCreatedAt.Default.(func() time.Time)
	// questionDescUpdatedAt is the schema descriptor for updated_at field.
	questionDescUpdatedAt := questionMixinFields0[1].Descriptor()
	// question.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	question.DefaultUpdatedAt = questionDescUpdatedAt.Default.(func() time.Time)
	// question.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	question.UpdateDefaultUpdatedAt = questionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// questionDescInterviewID is the schema descriptor for interview_id field.
	questionDescInterviewID := questionFields[0].Descriptor()
	// question.InterviewIDValidator is a validator for the "interview_id" field. It is called by the builders before save.
	question.InterviewIDValidator = questionDescInterviewID.Validators[0].(func(string) error)
	// questionDescContent is the schema descriptor for content field.
	questionDescContent := questionFields[2].Descriptor()
	// question.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	question.ContentValidator = questionDescContent.Validators[0].(func(string) error)
}
